name: 'Determine the Cluster'
description: 'Determines the Cluster based on the Environment'
inputs:
  environment:
    description: 'The selected Environment'
    required: true
  clusters:
    description: 'The possible Clusters'
    required: false
    default: 'dev, int, prod'
outputs:
  cluster:
    description: 'The determined Cluster. '
    value: ${{ steps.determineCluster.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: DetermineCluster
      id: determineCluster
      shell: bash
      run: |
        # Split the clusters string into an array
        IFS=', ' read -r -a clusters <<< "${{ inputs.clusters }}"

        # Set the default result if none of the clusters matches
        echo "result=Unknown" >> $GITHUB_OUTPUT

        # Check if any cluster is a prefix of the environment string
        for cluster in "${clusters[@]}"; do
          if [[ "${{ inputs.environment }}" == *"$cluster"* ]]; then
            echo "result=$cluster" >> $GITHUB_OUTPUT
            break
          fi
        done