name: 'Get & Cache Dependencies'
description: '...'
inputs:
  forceInstall:
    description: '...'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.forceInstall != 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.forceInstall == 'true'
      run: npm ci
      shell: bash