name: Test
on:
  workflow_dispatch:
    inputs:
      stream:
        type: choice
        description: Select the stream
        required: true
        options:
          - dev2
          - dev1
          - int2
          - int1
          - prod

jobs:
  GetCluster:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Run custom Action
        id: runJS
        uses: ./.github/actions/determineCluster
        with:
          environment: ${{ inputs.stream }}
          clusters: 'dev, int, prod'
      - name: Output Result
        run: echo ${{ steps.runJS.outputs.cluster }}